# functions which serve to obtain quotients of a given group and verify that a group satisfies given relations

using Oscar
import Base.Iterators: product

const SmallGroupID = Tuple{ZZRingElem, ZZRingElem}

"""
Return the IDs of the quotients of the group `G`.
"""
function quotient_ids(G::PcGroup)::Vector{SmallGroupID}
    return [ small_group_identification(quo(G, K)[1]) for K in normal_subgroups(G) ] # take the first coordinate of quo as the return of quo includes the homorphism for the quotient
end

"""
Return true if the group `G` is generated by some `d` elements satisfying the relations `rels`, and `false` otherwise.
"""
function satisfy_rels(rels::Vector{FPGroupElem}, G::PcGroup, d::Int)::Bool
    return any(
        let vx = collect(tx)
            all( is_one(map_word(r, vx)) for r in rels ) && G == sub(G, vx)[1]
        end
        for tx in product(fill(G, d)...)
    )
end
